version: '3.8'

services:

  redis-cart:
    image: redis:alpine
    container_name: redis-cart
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  emailservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice:v0.10.3
    environment:
      - PORT=8080
      - DISABLE_PROFILER=1
      - ENABLE_TRACING=1
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
    ports:
      - "5000:8080"

  productcatalogservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice:v0.10.3
    environment:
      - PORT=3550
      - DISABLE_PROFILER=1
      - ENABLE_TRACING=1
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
    ports:
      - "3550:3550"

  currencyservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice:v0.10.3
    environment:
      - PORT=7000
      - ENABLE_TRACING=1
      - DISABLE_PROFILER=1
      - COLLECTOR_SERVICE_ADDR=otel-collector:4318
    ports:
      - "7000:7000"

  paymentservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice:v0.10.3
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1
      - ENABLE_TRACING=1
      - COLLECTOR_SERVICE_ADDR=grpc://otel-collector:4317
    ports:
      - "50051:50051"

  shippingservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice:v0.10.3
    environment:
      - PORT=50051
      - DISABLE_PROFILER=1
    ports:
      - "50052:50051"

  recommendationservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice:v0.10.3
    environment:
      - PORT=8080
      - DISABLE_PROFILER=1
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - ENABLE_TRACING=1
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
    ports:
      - "8081:8080"

  cartservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice:v0.10.3
    environment:
      - REDIS_ADDR=redis-cart:6379
    ports:
      - "7070:7070"

  checkoutservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice:v0.10.3
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:5000
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - ENABLE_TRACING=1
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317
    ports:
      - "5050:5050"

  adservice:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice:v0.10.3
    environment:
      - PORT=9555
    ports:
      - "9555:9555"

  frontend:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend:v0.10.3
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - SHOPPING_ASSISTANT_SERVICE_ADDR=shoppingassistantservice:80
      - ENABLE_PROFILER=0
      - ENABLE_TRACING=1
      - COLLECTOR_SERVICE_ADDR=otel-collector:4317

  loadgenerator:
    image: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator:v0.10.3
    depends_on:
      - frontend
    environment:
      - FRONTEND_ADDR=frontend:8080
      - USERS=10
      - RATE=1

  oteltui:
    image: ymtdzzz/otel-tui:latest
    container_name: otel-tui
    ports:
      - "9411:9411"
    stdin_open: true
    tty: true
    entrypoint: ["/otel-tui", "--enable-zipkin"]


  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

volumes:
  redis-data:
