apiVersion: v1
kind: Service
metadata:
  name: {{ include "currency.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "currency.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: grpc
  selector:
    {{- include "currency.selectorLabels" . | nindent 4 }}
