apiVersion: v1
kind: Service
metadata:
  name: {{ include "email.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "email.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: grpc
  selector:
    {{- include "email.selectorLabels" . | nindent 4 }}
